### PR TITLE
[PATCH v3] Merge and port odp-linux patches up to 12b675595

### PR DESCRIPTION
**Pull request by matiaselo**

### CODE REVIEW

**Comment by JereLeppanen** [comment]
Why is the last patch ("validation: ipsec: fix termination when inline processing is not supported") not marked as a ported patch?

**Comment by matiaselo** [comment]
> Why is the last patch ("validation: ipsec: fix termination when inline processing is not supported") not marked as a ported patch?

It's a cherry picked newer commit from the linux-generic repo. It is required to successfully pass the CI tests.

**Comment by matiaselo** [comment]
@JereLeppanen Any additional comments? Once this PR is merged I can start working on the next merge PR.

**Comment by JereLeppanen** [comment]
No more comments from me. Looks OK to me, but perhaps @psavol should approve.

**Review by JereLeppanen — APPROVED** [review]

**Pull request merged**
